name: "ci"

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
#        platform: [windows-latest, macos-latest, ubuntu-latest]
        platform: [macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Eigen
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        ubuntu: |
          apt: libeigen3-dev
        macos: |
          brew: eigen
        windows: |
          github:
          - path: eigenteam/eigen-git-mirror
            ref: 3.3.7

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Run tests
      run: pytest tests/
